ACTIVATE_HTTPS: false
ANDROID_OAUTH2_SECRET: EdP3I6guUZZSB8zFsm0uwFvi
CMS_HOST: uat-csm.pratian.com
CONTACT_EMAIL: contact@uat-lms.pratian.com
ID: 3bAaEDezZCCAwdgvxbyxlCNS
LANGUAGE_CODE: en
LMS_HOST: uat-lms.pratian.com
MYSQL_ROOT_PASSWORD: NSK3lAiE
OPENEDX_MYSQL_PASSWORD: 2GjJinXu
OPENEDX_SECRET_KEY: ikoBijnDSRftgurcByizW0zJ
PLATFORM_NAME: EDX
