version: "3.7"

x-openedx-service:
  &openedx-service
  image: docker.io/overhangio/openedx-dev:3.11.3
  environment:
    SETTINGS: ${TUTOR_EDX_PLATFORM_SETTINGS:-tutor.development}
  volumes:
    # theme files
    - ../build/openedx/themes:/openedx/themes
    # editable requirements
    - ../build/openedx/requirements:/openedx/requirements

services:
  lms:
    <<: *openedx-service
    command: ./manage.py lms runserver 0.0.0.0:8000
    ports:
        - "8000:8000"
  cms:
    <<: *openedx-service
    command: ./manage.py cms runserver 0.0.0.0:8000
    ports:
        - "8001:8000"
  lms_worker:
    <<: *openedx-service
  cms_worker:
    <<: *openedx-service
  
  # Additional service for watching theme changes
  watchthemes:
    <<: *openedx-service
    command: openedx-assets watch-themes --env dev
    restart: unless-stopped
  
  